### ISSUE TITLE
 Overwrites you aws/credentials

### ISSUE THREAD

**Issue by Keralin** [ivanfoo/joe#1]
When you use Mortadelo it also overwrites your credentials. There should be a warning or something.

**Comment by ivanfoo** [comment]
Yeap @Keralin, the tool is very basic right now, I'll fix this issue and a few more in the next release

**Comment by ivanfoo** [comment]
Hey @Keralin, the version v0.1.1 fixes that.

**Comment by Keralin** [comment]
Yep now its working good, ty @ivanfoo
